### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by scalp42** [scalyr/scalyr-tool#39]
Hi folks,

Running into an issue here:

```
Beginning live tail..
Using arguments: Namespace(command='tail', filter='$chef_environment contains "prod"', lines=10, no_escape_unicode=True, output='multiline', proxy=None, server=None, token='', verbose=True)
No proxy configuration found
Connecting to www.scalyr.com via https
Request headers:
  Content-type: application/json
Request body:
{
  "columns": "",
  "endTime": 1620425610,
  "filter": "$chef_environment contains \"prod\"",
  "maxCount": 1000,
  "pageMode": "tail",
  "priority": "low",
  "queryType": "log",
  "startTime": 1620425010,
  "token": "xxxxxx"
}
Traceback (most recent call last):
  File "/usr/local/bin/scalyr", line 742, in <module>
    command_func(parser)
  File "/usr/local/bin/scalyr", line 495, in commandTail
    liveTail(apiToken, args)
  File "/usr/local/bin/scalyr", line 446, in liveTail
    "priority": "low"
  File "/usr/local/bin/scalyr", line 172, in sendRequest
    conn.request("POST", uri, parameterJson, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

Any ideas how to work around that?

**Comment by weilliu** [comment]
@scalp42 Could you send me the entire command your use to get the exception (with API token redacted)? I want to try to reproduce it locally.

**Comment by scalp42** [comment]
@weilliu `scalyr --verbose tail '$chef_environment contains "prod"' --output multiline`

**Comment by weilliu** [comment]
I am not able to reproduce the issue locally using the exact same command. I use the read token that ends with `poE-`. Could you give it another try?
```
weilil@C02F348AMD6R scalyr-tool % ./scalyr --verbose tail '$chef_environment contains "prod"' --output multiline --token XXXpoE-
Beginning live tail..
Using arguments: Namespace(command='tail', filter='$chef_environment contains "prod"', lines=10, no_escape_unicode=True, output='multiline', server=None, token='0I07J5M7g1GbteOXD27fUbUOpKehEsBRGUeLpLqN9poE-', verbose=True)
Connecting to www.scalyr.com via https
Request headers:
  Content-type: application/json
Request body:
{
  "columns": "",
  "endTime": 1620436073,
  "filter": "$chef_environment contains \"prod\"",
  "maxCount": 1000,
  "pageMode": "tail",
  "priority": "low",
  "queryType": "log",
  "startTime": 1620435473,
  "token": "XXXpoE-"
}
After 1.336 seconds, Scalyr server returned 2051558 bytes; status 200 / 
2021-05-07 18:07:49: I {"fabio_request_id":"05faa985-6210-6bc1-cd05-b4d5d6c060ee","platform_core_":{"method":"GET","path":"/api/job_requests/near_with_details","format":"json","controller":"InternalAPI::V2::JobRequestsController","action":"near_with_details","status":200,"duration":1248.01,"view":29.39,"db":0.0,"params":{"search_radius":"75","limit":"10","next_page":"eyJmaXJzdF9jYWxsX2F0IjoiMjAyMS0wNS0wN1QxODowNTozOC42NzUtMDc6MDAiLCJzZWFyY2hfY29vcmRpbmF0ZXMiOlsiNDAuODI1OTI1IiwiLTczLjk1MjI1MzEiXSwidXNlcl9jb29yZGluYXRlcyI6bnVsbCwicmFkaXVzIjoyMDAsImZpbHRlciI6e30sIm9yZGVyX2J5Ijoic3RhcnRfdGltZSBhc2MsIGpvYl9yZXF1ZXN0cy5pZCBkZXNjIiwic29ydF9maWVsZCI6InN0YXJ0X3RpbWUiLCJsaW1pdCI6MTAsImxhc3Rfc29ydF92YWx1ZSI6IjIwMjEtMDUtMTBUMDY6MDA6MDAuMDAwLTA3OjAwIiwibGFzdF9tZGpfaWQiOjE2NDMwMiwibGFzdF9pZCI6MTkwNDQwOH0=","auth_token":"[FILTERED]","format":"json"},"current_admin_user_id":null,"current_user_id":361392,"pid":11,"tid":"2fcg","level":"INFO"}}
```

**Comment by scalp42** [comment]
@weilliu strange same issue, can confirm token ends with `N9poE-`.

Which host is it trying to access exactly?

**Comment by weilliu** [comment]
Based on the response, it seems that `www.scalyr.com` is the host that it's trying to connect with. 
I'd suggest you to re-downlod it from the repo and see if the issue persists.
```
curl https://raw.githubusercontent.com/scalyr/scalyr-tool/master/scalyr > scalyr
chmod u+x scalyr
./scalyr --verbose tail '$chef_environment contains "prod"' --output multiline --token XXXN9poE-
```
Another thing you could try is to upgrade your python version. I am on `2.7.16` , so any versions that are higher than that (including python3) should work.

**Comment by scalp42** [comment]
I double checked the host in Safari no issues and I actually just re-downloaded the tool when I opened the issue.

![image](https://user-images.githubusercontent.com/1475276/117552644-8b181800-b001-11eb-88ee-b21634edd32b.png)

EDIT: I changed the first line to point to python3 and it's working

**Comment by weilliu** [comment]
@scalp42  I am glad to hear that it's resolved. Could you confirm which line you changed? I can file a ticket to track the issue in case this is consistently reproducible with python2. Thanks.

**Comment by scalp42** [comment]
I just pointed it to python3 that's it:

```
#!/usr/bin/env python3
```

**Comment by weilliu** [comment]
I created an internal ticket to track the issue. Thank you!
